### ISSUE TITLE
Uncaught TypeError: Cannot read property 'authorize' of undefined

### ISSUE THREAD

**Issue by 4abhinavjain** [be-cloud-js/open-erp-modules#14]
Hi Jerome,

I tried your module today and it is not working. I am getting the following error-

`https://progsoul.prognoix.com/web/content/535-4793f7b/web.assets_backend.js:2948
Traceback:
TypeError: Cannot read property 'authorize' of undefined
    at Object.<anonymous> (https://progsoul.prognoix.com/web/content/535-4793f7b/web.assets_backend.js:2948:280)
    at Object.<anonymous> (https://progsoul.prognoix.com/web/content/251-aeb8085/web.assets_common.js:547:681)
    at fire (https://progsoul.prognoix.com/web/content/251-aeb8085/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://progsoul.prognoix.com/web/content/251-aeb8085/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) (https://progsoul.prognoix.com/web/content/251-aeb8085/web.assets_common.js:548:56)
    at fire (https://progsoul.prognoix.com/web/content/251-aeb8085/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://progsoul.prognoix.com/web/content/251-aeb8085/web.assets_common.js:546:198)
    at Object.<anonymous> (https://progsoul.prognoix.com/web/content/251-aeb8085/web.assets_common.js:547:874)
    at fire (https://progsoul.prognoix.com/web/content/251-aeb8085/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://progsoul.prognoix.com/web/content/251-aeb8085/web.assets_common.js:546:198)`

I crosschecked several times. The Drive and picker API are on. And I am using the same Client ID as the google calendar on Odoo.

You help will be highly appreciated.

Thanks,
AJ

**Comment by letzdoo-js** [comment]
Hello,

Could you please enable the developper mode and post the stack trace ?

Which version of Odoo are you using 9,10,11 ? CE ou EE ?

Jerome

**Comment by pamaillotte** [comment]
I have the same issue :
http://extranet.evolutis.fr/web/content/2280-d672af4/web.assets_backend.js:2972
Retraçage :
TypeError: Cannot read property 'authorize' of undefined
    at Object.<anonymous> (http://extranet.evolutis.fr/web/content/2280-d672af4/web.assets_backend.js:2972:280)
    at Object.<anonymous> (http://extranet.evolutis.fr/web/content/2209-b7b7ce7/web.assets_common.js:547:681)
    at fire (http://extranet.evolutis.fr/web/content/2209-b7b7ce7/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://extranet.evolutis.fr/web/content/2209-b7b7ce7/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) (http://extranet.evolutis.fr/web/content/2209-b7b7ce7/web.assets_common.js:548:56)
    at fire (http://extranet.evolutis.fr/web/content/2209-b7b7ce7/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://extranet.evolutis.fr/web/content/2209-b7b7ce7/web.assets_common.js:546:198)
    at Object.<anonymous> (http://extranet.evolutis.fr/web/content/2209-b7b7ce7/web.assets_common.js:547:874)
    at fire (http://extranet.evolutis.fr/web/content/2209-b7b7ce7/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (http://extranet.evolutis.fr/web/content/2209-b7b7ce7/web.assets_common.js:546:198)

On Odoo 10 CE

**Comment by 4abhinavjain** [comment]
@be-cloud-js 

With I'm not completely sure on how to take the traceback in Odoo. Following is the console output from google chrome of the page -
`Failed to load resource: the server responded with a status of 404 () 
https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_US.sMif956eGwE.O/m=picker/exm=auth2/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCM1OIOGZAQMGtxjf_HPMu-fT-spbA/cb=gapi.loaded_1
 Failed to load resource: the server responded with a status of 404 ()
apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_US.sMif956eGwE.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCM1OIOGZAQMGtxjf_HPMu-fT-spbA/cb=gapi.loaded_0
gdrive.js:46 Uncaught TypeError: Cannot read property 'authorize' of undefined
    at Object.<anonymous> (https://progsoul.prognoix.com/document_gdrive/static/src/js/gdrive.js:46:43)
    at Object.<anonymous> (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3276:89)
    at fire (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3321:62)
    at fire (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3283:104)
    at fire (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3231:49)
gdrive.js:46 Uncaught TypeError: Cannot read property 'authorize' of undefined
    at Object.<anonymous> (https://progsoul.prognoix.com/document_gdrive/static/src/js/gdrive.js:46:43)
    at Object.<anonymous> (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3276:89)
    at fire (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3321:62)
    at fire (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3283:104)
    at fire (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (https://progsoul.prognoix.com/web/static/lib/jquery/jquery.js:3231:49)`

Does that help?

I'm also running Odoo 10 CE (updated to 13th Dec 17)

**Comment by letzdoo-js** [comment]
Hello,

I did my homework and tested the module on both 9.0 and 10.0 CE.

I had to upgrade the gapi.js to get it working in 10.0 but both are working for me.

Would love to help you getting it working.

Jerome

**Comment by letzdoo-js** [comment]
ps : The 404 seems related to the gapi.js issue, please pull the change and let me know.

Jerome

**Comment by pamaillotte** [comment]
Hi,

thanks Jerome.
There is no change on git. I change the gapi.js and i have the same issue.

**Comment by eLBati** [comment]
@be-cloud-js Hi, where did you upload the changes? As @pamaillotte said, we can't find any update on branches 10.0, 9.0 nor master.
Thanks
