### ISSUE TITLE
document_gdrive for OE 10

### ISSUE THREAD

**Issue by mcassuto** [be-cloud-js/open-erp-modules#7]
Hi,

I am unable to make this module to work:

On v10 CE, after installation and configuration, each time I try to access a form view, I got the following error:
```
Uncaught Error: QWeb2: Template 'AddGDriveDocumentItem' not found
https://v10ce.archeti.ca/web/content/435-c016c08/web.assets_common.js:2908
Retraçage :
Error: QWeb2: Template 'AddGDriveDocumentItem' not found
    at Object.exception (https://v10ce.archeti.ca/web/content/435-c016c08/web.assets_common.js:2908:7)
    at Engine._render (https://v10ce.archeti.ca/web/content/435-c016c08/web.assets_common.js:2952:103)
    at Engine.render (https://v10ce.archeti.ca/web/content/435-c016c08/web.assets_common.js:2948:151)
    at Class.redraw (https://v10ce.archeti.ca/web/content/1020-cde14fd/web.assets_backend.js:2947:207)
    at Class.redraw (https://v10ce.archeti.ca/web/content/435-c016c08/web.assets_common.js:3012:371)
    at Class.start (https://v10ce.archeti.ca/web/content/1020-cde14fd/web.assets_backend.js:1935:888)
    at Class.prototype.(anonymous function) [as start] (https://v10ce.archeti.ca/web/content/435-c016c08/web.assets_common.js:3009:559)
    at https://v10ce.archeti.ca/web/content/435-c016c08/web.assets_common.js:3112:963
    at https://v10ce.archeti.ca/web/content/435-c016c08/web.assets_common.js:547:681
    at fire (https://v10ce.archeti.ca/web/content/435-c016c08/web.assets_common.js:541:299)
```
On v10 EE, I do not get this error:
* When I upload the file, nothing happens, the file is attached to the Odoo record, but nothing appears in the GDrive
* When I click the action "From Gdrive....", I receive the following error:
```
Uncaught TypeError: Cannot read property 'auth' of undefined
https://tests.torngats.ca/web/content/866-acdaf70/web.assets_backend.js:3091
Retraçage :
TypeError: Cannot read property 'auth' of undefined
    at Object.<anonymous> (https://tests.torngats.ca/web/content/866-acdaf70/web.assets_backend.js:3091:226)
    at Object.<anonymous> (https://tests.torngats.ca/web/content/608-68089ea/web.assets_common.js:547:681)
    at fire (https://tests.torngats.ca/web/content/608-68089ea/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://tests.torngats.ca/web/content/608-68089ea/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) (https://tests.torngats.ca/web/content/608-68089ea/web.assets_common.js:548:56)
    at fire (https://tests.torngats.ca/web/content/608-68089ea/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://tests.torngats.ca/web/content/608-68089ea/web.assets_common.js:546:198)
    at Object.<anonymous> (https://tests.torngats.ca/web/content/608-68089ea/web.assets_common.js:547:874)
    at fire (https://tests.torngats.ca/web/content/608-68089ea/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://tests.torngats.ca/web/content/608-68089ea/web.assets_common.js:546:198)
```

I do not even find a way to confirm the credentials are ok.

Any help, would be really appreciated...

**Comment by dagoodma** [comment]
I'm having the same issue when I click "From Gdrive...":

```
https://my.odoo-site.com/web/content/561-4fe6cbb/web.assets_backend.js:2956
Traceback:
TypeError: Cannot read property 'auth' of undefined
    at Object.<anonymous> (https://my.odoo-site.com/web/content/561-4fe6cbb/web.assets_backend.js:2956:226)
    at Object.<anonymous> (https://my.odoo-site.com/web/content/265-ac0958f/web.assets_common.js:547:681)
    at fire (https://my.odoo-site.com/web/content/265-ac0958f/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://my.odoo-site.com/web/content/265-ac0958f/web.assets_common.js:546:198)
    at Object.deferred.(anonymous function) (https://my.odoo-site.com/web/content/265-ac0958f/web.assets_common.js:548:56)
    at fire (https://my.odoo-site.com/web/content/265-ac0958f/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://my.odoo-site.com/web/content/265-ac0958f/web.assets_common.js:546:198)
    at Object.<anonymous> (https://my.odoo-site.com/web/content/265-ac0958f/web.assets_common.js:547:874)
    at fire (https://my.odoo-site.com/web/content/265-ac0958f/web.assets_common.js:541:299)
    at Object.fireWith [as resolveWith] (https://my.odoo-site.com/web/content/265-ac0958f/web.assets_common.js:546:198)
```

I think the error comes form here: `document_gdrive/static/src/js/gdrive.js`, because on line 26 I see:
```javascript
gapi.load('auth', {
```

which would mean that **gapi** is undefined. See here: https://stackoverflow.com/questions/31144874/gapi-is-not-defined-google-sign-in-issue-with-gapi-auth2-init

I think the issue is with loading the **gapi** from google API.  Maybe the interface has changed and the script must be loaded differently now?  I'm not sure but I'm going to dig into this and maybe create a pull request if I can figure it out.

**Comment by dagoodma** [comment]
Okay. I got it to work. See my pull request #9

**Comment by alessiom72** [comment]
Hi,
we would like to use the module, with Odoo 10 and the "Material/United Backend Theme". We have downloaded the last version from GitHub, but we always get the error:
`Uncaught TypeError: Cannot read property 'auth' of undefined`
We have tried to uninstall the "Material/United Backend Theme" without luck.
Could someone help us?

Thank you very much
Alessio

**Comment by clickode** [comment]
Hi there, same problem here. Cannot read property 'auth' of undefined.
Is there any workaround?
Thanks in advance
